spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: 